version: "3.8"

services:
  mongo-db:
    image: mongo:5.0
    container_name: mongo-db
    volumes:
      - mongo-log:/var/log/mongodb
      - mongo-data:/data/db
    # restart: always
    ports:
      - 27017:27017
    networks:
      - iot

  om2m:
    image: smartcityresearch/ctop-om2m:latest
    container_name: om2m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8080:8200
    depends_on:
      - mongo-db
    # restart: always
    environment:
      - MONGO_URL=mongo-db:27017
      - MONGO_USER=om2m
      - MONGO_PASSWORD=om2m
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
    networks:
      - iot

networks:
  iot:

volumes:
  mongo-data:
  mongo-log:
